"""empty message

Revision ID: 106e9e5e7234
Revises: None
Create Date: 2015-08-28 16:01:13.578047

"""

# revision identifiers, used by Alembic.
revision = '106e9e5e7234'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'author_id')
    ### end Alembic commands ###
