"""empty message

Revision ID: 3282aeb12e0b
Revises: 448d7b9877d3
Create Date: 2015-08-28 17:41:21.045478

"""

# revision identifiers, used by Alembic.
revision = '3282aeb12e0b'
down_revision = '448d7b9877d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'posts_author_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_author_fkey', 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
