"""empty message

Revision ID: 448d7b9877d3
Revises: 451798ff234a
Create Date: 2015-08-28 17:00:30.590344

"""

# revision identifiers, used by Alembic.
revision = '448d7b9877d3'
down_revision = '451798ff234a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'author')
    ### end Alembic commands ###
