"""empty message

Revision ID: 451798ff234a
Revises: 106e9e5e7234
Create Date: 2015-08-28 16:51:33.188666

"""

# revision identifiers, used by Alembic.
revision = '451798ff234a'
down_revision = '106e9e5e7234'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(u'users_author_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_author_id_fkey', 'users', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
